name: Auto Create Packages on OBS

on:
  create:
  push:
    branches:
      create:


jobs:
  create_pkg:
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
