name: Format files

on:
  push:
    branches:
      - *

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Format the PKGBUILD
        uses: collin-miller/shfmt-action@v1
        with:
          args: -d ./PKGBUILD

      - name: Upload changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format files
